-- MySQL Script generated by MySQL Workbench
-- Thu Dec  8 12:42:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DondeEstanApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DondeEstanApp` ;
USE `DondeEstanApp` ;

-- -----------------------------------------------------
-- Table `DondeEstanApp`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DondeEstanApp`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `id_number` LONGBLOB NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `enabled` BOOLEAN NOT NULL DEFAULT TRUE,
  `type` VARCHAR(45) NOT NULL CHECK (type='observed' OR type='observer'),
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DondeEstanApp`.`SchoolBuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DondeEstanApp`.`SchoolBuses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `license_plate` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `school_bus_license` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DondeEstanApp`.`ObservedUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DondeEstanApp`.`ObservedUsers` (
  `privacy_key` VARCHAR(45) NOT NULL,
  `company_name` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `school_bus_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  INDEX `fk_ObservedUsers_Users_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `privacyKey_UNIQUE` (`privacy_key` ASC) VISIBLE,
  INDEX `fk_ObservedUsers_School_Buses_idx` (`school_bus_id` ASC) VISIBLE,
  CONSTRAINT `fk_ObservedUsers_Users`
    FOREIGN KEY (`user_id`)
    REFERENCES `DondeEstanApp`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ObservedUsers_School_Buses`
    FOREIGN KEY (`school_bus_id`)
    REFERENCES `DondeEstanApp`.`SchoolBuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DondeEstanApp`.`ObserverUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DondeEstanApp`.`ObserverUsers` (
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  INDEX `fk_ObserverUsers_Users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_ObserverUsers_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `DondeEstanApp`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DondeEstanApp`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DondeEstanApp`.`Addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `floor` VARCHAR(5) NULL DEFAULT NULL,
  `apartament` VARCHAR(45) NULL DEFAULT NULL,
  `zipCode` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `latitude` VARCHAR(45) NOT NULL,
  `longitude` VARCHAR(45) NOT NULL,
  `observer_user_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_Addresses_ObserverUsers1_idx` (`observer_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Addresses_ObserverUsers1`
    FOREIGN KEY (`observer_user_id`)
    REFERENCES `DondeEstanApp`.`ObserverUsers` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DondeEstanApp`.`ObservedUsers_ObserverUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DondeEstanApp`.`ObservedUsersObserverUsers` (
  `observed_user_id` INT NOT NULL,
  `observer_user_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`observer_user_id`, `observed_user_id`),
  INDEX `fk_ObservedUsersObserverUsers_ObservedUsers_idx` (`observed_user_id` ASC) VISIBLE,
  INDEX `fk_ObservedUsersObserverUsers_ObserverUsers_idx` (`observer_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_ObservedUsersObserverUsers_ObservedUsers_id`
    FOREIGN KEY (`observed_user_id`)
    REFERENCES `DondeEstanApp`.`ObservedUsers` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ObservedUsersObserverUsers_ObserverUsers_id`
    FOREIGN KEY (`observer_user_id`)
    REFERENCES `DondeEstanApp`.`ObserverUsers` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DondeEstanApp`.`Children`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DondeEstanApp`.`Children` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `school_name` VARCHAR(45) NOT NULL,
  `school_start_time` TIME NOT NULL,
  `school_end_time` TIME NOT NULL,
  `observer_user_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_children_observer_user_idx` (`observer_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_children_observer_user`
    FOREIGN KEY (`observer_user_id`)
    REFERENCES `DondeEstanApp`.`ObserverUsers` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
